version: '3.7'
services:
  selenoid:
    container_name: selenoid
    hostname: selenoid
    image: aerokube/selenoid:1.11.2
    networks:
      - selenoid
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/anton/selenoid/browsers.json:/etc/selenoid/browsers.json:ro
    command:
      - "-container-network=selenoid"
      - "-limit=12"

  ggr:
    container_name: ggr
    hostname: ggr
    depends_on:
      - selenoid
    image: aerokube/ggr:1.7.2
    networks:
      - selenoid
    volumes:
      - /etc/grid-router:/etc/grid-router:ro
    command:
      - "-guests-allowed"
      - "-guests-quota=selenoid"
      - "-verbose"
      - "-quotaDir=/etc/grid-router/quota"

  ggr-ui:
    container_name: ggr-ui
    hostname: ggr-ui
    depends_on:
      - ggr
    image: aerokube/ggr-ui:1.2.0
    networks:
      - selenoid
    volumes:
      - /etc/grid-router/quota:/etc/grid-router/quota:ro

  selenoid-ui:
    container_name: selenoid-ui
    hostname: selenoid-ui
    depends_on:
      - ggr-ui
    image: aerokube/selenoid-ui:1.10.11
    networks:
      - selenoid
    command:
      - "--selenoid-uri"
      - "http://ggr-ui:8888"

  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    privileged: true
    hostname: nginx
    networks:
      - selenoid  
    depends_on:
      - jenkins
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - /etc/localtime:/etc/localtime
    ports:
      - "80:80"

  registry:
     image: registry:latest
     restart: always
     container_name: registry
     hostname: registry
     networks:
       - selenoid  
     volumes:
       - ./registry:/var/lib/registry
     ports:
       - "5005:5005"
     environment:
       - REGISTRY_HTTP_ADDR=0.0.0.0:5005

  jenkins:
    image: jenkins/jenkins:jdk17
    restart: always
    hostname: jenkins
    user: root
    ports:
      - "8090:8080"
    networks:
      - selenoid
    environment:
      - JAVA_OPTS="-Dhudson.model.DownLoadService.noSignatureCheck=true"
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  selenoid:
    name: selenoid
